version: '3.7'
services:
  ttt-dynamo:
    image: amazon/dynamodb-local
    container_name: ttt-dynamo
    hostname: dynamodb
    restart: always
    volumes:
      - ./my-dynamodb-data:/home/dynamodblocal/data
    ports:
      - 8000:8000
    command: '-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data/'
